AppName: borg
entryPoint: scripts/borg/borg-client-side.ps1
HostName: 192.168.33.110
SshPort: 22
ServerName: 测试机
coreNumber: 8
mem: 8G
UserName: root
LogDir: e:/backups/logs
BorgBin: /usr/local/bin/borg
BorgInit: "%s init --encryption=none %s"
BorgCreate: '%s create --stats --json %s::%s /etc /usr/local/bin'
BorgPrune: '%s prune -v --list --keep-daily=7 --keep-weekly=4 %s'
BorgList: '%s list --json %s'
BorgRepoPath: /opt/repo
LocalDir: e:/backups/borg
taskcmd:
  archive: '%s -Action ArchiveAndDownload -ConfigFile %s -LogResult -Json'
  prune: '%s -Action PruneAndDownload -ConfigFile %s -LogResult -Json'
  backuplocal: '%s -Action BackupLocal -ConfigFile %s -LogResult -Json'
  diskfree: '%s -Action DiskFree -ConfigFile %s -LogResult -Json'
  memoryfree: '%s -Action MemoryFree -ConfigFile %s -LogResult -Json'
crons:
  archive: 0/10 * * * * ? *
  diskfree: 3 33 22 * * ? *
  prune: 3 33 1 ? * SAT *
  backuplocal: 3 * * ? * * *
BorgPrunePattern: 0 3 0 3 0 0 2
Softwares:
  - PackageUrl: https://github.com/borgbackup/borg/releases/download/1.1.7/borg-linux64
    LocalName:
    InstallDetect:
      command: yum list installed | Where-Object {$_ -match 'mysql57-community-release.noarch'}
      expect: aru
      unexpect:
    Install:
      command: yum --nogpgcheck -y localinstall {filepath}
UninstallCommand: yum remove -y (Invoke-Expression -Command '& yum list installed' | ForEach-Object {$_ -split '\\s+' | Select-Object -First 1 }| Where-Object {$PSItem -like '*mysql*server.x86_64'})
PackageDir: /tmp/easyinstaller-scripts/packages
Software:
  InstallDetect:
    command: systemctl status mysqld
    expect:
    unexpect: not-found
